
development:
  adapter: postgresql
  database: my_alum_database_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: my_alum_database_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: my_alum_database_production
  pool: 5
  timeout: 5000
